# Generated by Django 5.1.15 on 2026-09-22 05:34

import apps.cycles.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_date', models.DateField(default=apps.cycles.models.get_current_week_start)),
                ('status', models.CharField(choices=[('COLLECTING', 'Collecting Feedback'), ('RETROSPECTIVE', 'Retrospective'), ('COMPLETED', 'Completed')], default='COLLECTING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitated_cycles', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='projects.project')),
            ],
            options={
                'verbose_name': 'Feedback Cycle',
                'verbose_name_plural': 'Feedback Cycles',
                'ordering': ['-week_date', '-created_at'],
            },
        ),
    ]
