# Generated by Django 5.1.15 on 2026-09-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0002_feedbackcard'),
        ('retrospectives', '0002_topiccluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcard',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='retrospectives.topiccluster'),
        ),
    ]
