# Generated by Django 5.1.15 on 2026-09-22 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0002_feedbackcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrospectiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('REVEAL', 'Reveal'), ('CLUSTER', 'Cluster'), ('VOTE', 'Vote'), ('DISCUSS', 'Discuss'), ('SUMMARY', 'Summary')], default='REVEAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retro_session', to='cycles.feedbackcycle')),
            ],
            options={
                'verbose_name': 'Retrospective Session',
                'verbose_name_plural': 'Retrospective Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
