# Generated by Django 5.1.15 on 2026-09-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrospectives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='retrospectives.retrospectivesession')),
            ],
            options={
                'verbose_name': 'Topic Cluster',
                'verbose_name_plural': 'Topic Clusters',
                'ordering': ['created_at'],
            },
        ),
    ]
