# Generated by Django 5.1.15 on 2026-09-22 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrospectives', '0002_topiccluster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='retrospectives.topiccluster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cluster Vote',
                'verbose_name_plural': 'Cluster Votes',
                'ordering': ['created_at'],
            },
        ),
    ]
