# Generated by Django 5.1.15 on 2026-09-22 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrospectives', '0003_clustervote'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISCUSSED', 'Discussed'), ('SKIPPED', 'Skipped'), ('DEFERRED', 'Deferred')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_topic', to='retrospectives.topiccluster')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_topics', to='retrospectives.retrospectivesession')),
            ],
            options={
                'verbose_name': 'Discussion Topic',
                'verbose_name_plural': 'Discussion Topics',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
