from django.conf import settings
from django.db import models


class RetrospectiveSession(models.Model):
    """Real-time retrospective meeting session for an active feedback cycle."""

    class Stage(models.TextChoices):
        REVEAL = "REVEAL", "Reveal"
        CLUSTER = "CLUSTER", "Cluster"
        VOTE = "VOTE", "Vote"
        DISCUSS = "DISCUSS", "Discuss"
        SUMMARY = "SUMMARY", "Summary"

    cycle = models.OneToOneField(
        "cycles.FeedbackCycle",
        on_delete=models.CASCADE,
        related_name="retro_session",
    )
    current_stage = models.CharField(
        max_length=20,
        choices=Stage.choices,
        default=Stage.REVEAL,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Retrospective Session"
        verbose_name_plural = "Retrospective Sessions"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Retro for {self.cycle.project.name} (Week of {self.cycle.week_date}) - {self.get_current_stage_display()}"


class TopicCluster(models.Model):
    """Thematic grouping of feedback cards generated by AI or organized by team."""

    session = models.ForeignKey(
        RetrospectiveSession,
        on_delete=models.CASCADE,
        related_name="clusters",
    )
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, default="")
    is_ai_generated = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Topic Cluster"
        verbose_name_plural = "Topic Clusters"
        ordering = ["created_at"]

    def __str__(self):
        return self.title


class ClusterVote(models.Model):
    """An individual vote cast by a team member on a topic cluster."""

    cluster = models.ForeignKey(
        TopicCluster,
        on_delete=models.CASCADE,
        related_name="votes",
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="cluster_votes",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Cluster Vote"
        verbose_name_plural = "Cluster Votes"
        ordering = ["created_at"]

    def __str__(self):
        return f"Vote by {self.user.username} on {self.cluster.title}"


class DiscussionTopic(models.Model):
    """An ordered topic in the retrospective discussion agenda, derived from a topic cluster and vote tallies."""

    class Status(models.TextChoices):
        PENDING = "PENDING", "Pending"
        DISCUSSED = "DISCUSSED", "Discussed"
        SKIPPED = "SKIPPED", "Skipped"
        DEFERRED = "DEFERRED", "Deferred"

    session = models.ForeignKey(
        RetrospectiveSession,
        on_delete=models.CASCADE,
        related_name="discussion_topics",
    )
    cluster = models.OneToOneField(
        TopicCluster,
        on_delete=models.CASCADE,
        related_name="discussion_topic",
        null=True,
        blank=True,
    )
    title = models.CharField(max_length=255)
    vote_count = models.PositiveIntegerField(default=0)
    order = models.PositiveIntegerField(default=0)
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Discussion Topic"
        verbose_name_plural = "Discussion Topics"
        ordering = ["order", "created_at"]

    def __str__(self):
        return f"#{self.order} {self.title} ({self.vote_count} votes) - {self.get_status_display()}"
